version: '3'
services:
  elasticsearch:
    image: elasticsearch:7.7.0
    ports: 
      - 9200:9200
    environment:
      - "discovery.type=single-node"
  kibana:
    image: kibana:7.7.0
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch
  fluentd:
    build: ./fluentd
    volumes:
      - ./fluentd/conf:/fluentd/etc
    ports:
      - "24224:24224"
      - "24224:24224/udp"
    depends_on:
      - elasticsearch
  web:
    image: nginx:stable
    ports:
      - 80:80
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: nginx.access
    depends_on: 
      - fluentd
